[main]
include=~/.config/foot/themes/noctalia
# font=GeistMono Nerd Font:size=12
# font=IoskeleyMono Nerd Font Mono:size=12:fontfeatures=zero
font=LythMonoTerm Nerd Font:size=12
# font=JetBrainsMono Nerd Font:size=12


[colors-dark]
alpha=0.99
blur=yes
