[main]
include=~/.config/foot/themes/noctalia
# font=GeistMono Nerd Font:size=12
# font=IoskeleyMonoTerm Nerd Font Mono:size=12
font=JetBrainsMono Nerd Font:size=12


[colors-dark]
alpha=0.99
blur=yes
